### ISSUE TITLE
In which file to read the source code implementation of El-Attention for self-attention

### ISSUE THREAD

**Issue by ADaBenxiong** [microsoft/fastseq#119]
Hello, thank you very much for your outstanding work.
We want to read the implementation of EL-Attention source code about self-attention, but we haven't found the relevant source code implementation. In which folder should we read the source code implementation of EL-Attention.
Thanks a lot

**Comment by yuyan2do** [comment]
Please see implementation in https://github.com/microsoft/fastseq/blob/main/fastseq/optimizer/fairseq/el_attention_optimizer.py
