### ISSUE TITLE
ModuleNotFoundError: No module named 'fastseq.models' 

### ISSUE THREAD

**Issue by f-lng** [microsoft/fastseq#78]
Hello,

The fastseq library, installed through pip, seems to have the models directory missing and crashes with the following exception:

>File "/root/miniconda3/envs/Env37/lib/python3.7/site-packages/fastseq/__init__.py", line 9, in <module>
>   import fastseq.models  # pylint: disable=wrong-import-position
>ModuleNotFoundError: No module named 'fastseq.models' 

And while this directory can be found in the repository here, I can only find prophetnet, while I am looking for BART.
Could you give me a hint on how to install the according models?

Thanks and happy holidays :-)

**Comment by feihugis** [comment]
@f-lng Do you mean fastseq was installed by `pip install fastseq`? If yes, could you try the installation method mentioned [here](https://github.com/microsoft/fastseq#install-from-the-source)? The package on pypi.org is out of date. We are working on the manylinux support. After that, we will update the package there; if no, could you provide more details about how to reproduce this error?

Inside fastseq, BART related code can be found under the directory [fastseq/optimizer/](https://github.com/microsoft/fastseq/tree/main/fastseq/optimizer). You may find that fastseq did not implement BART from scratch, but it natively supports the ones huggingface-transformers and fairseq implement. You just need to add `import fastseq` to the beginning of your code which calls either huggingface-transformers BART or fairseq BART, then all the performance optimizations provided by fastseq will be automatically applied. A simple example can be found [here](https://github.com/microsoft/fastseq#use-source-code-for-speedup). The more comprehensive examples can be found [here](https://github.com/microsoft/fastseq/blob/main/tests/optimizer/transformers/test_bart_optimizer.py) for huggingface-transformers and [here ](https://github.com/microsoft/fastseq/blob/main/tests/optimizer/fairseq/test_fairseq_optimizer.py) for fairseq.

**Comment by f-lng** [comment]
Thank you, it seems that the pip package is indeed broken.
