### ISSUE TITLE
fairseq eval_lm

### ISSUE THREAD

**Issue by sshleifer** [microsoft/fastseq#87]
Have you guys looked at fairseq [eval_lm](https://github.com/pytorch/fairseq/blob/master/fairseq_cli/eval_lm.py)?

It's not generative, but I was wondering whether any of these tricks would work.
Thanks in advance!

**Comment by feihugis** [comment]
> Have you guys looked at fairseq [eval_lm](https://github.com/pytorch/fairseq/blob/master/fairseq_cli/eval_lm.py)?
> 
> It's not generative, but I was wondering whether any of these tricks would work.
> Thanks in advance!

@sshleifer I have run a quick test using the below command with/without FastSeq, but I did not see big speed difference. We will do more investigations.

```
python eval_lm.py  adaptive_lm_wiki103.v2/data-bin/ --path adaptive_lm_wiki103.v2/model.pt --sample-break-mode complete --max-tokens 3072 --context-window 2560 --softmax-batch 1024
```

**Comment by feihugis** [comment]
Close this issue. Please feel free to reopen it if there are more questions.
