### ISSUE TITLE
Does it support model seq2seq with encoder, and decoder base on lstm, bi-lstm?

### ISSUE THREAD

**Issue by trangtv57** [microsoft/fastseq#93]
Hi,
I want to inference my model seq2seq with encoder and decoder base on lstm, and bi-lstm. And i find out your project, all model in readme for sample of improve performance are transformer model base. And i not see other architecture like lstm, or conv? Can you confirm what's type of model can improve performance ?
Thankyou.

**Comment by feihugis** [comment]
Thanks @trangtv57 for your interest in FastSeq. Right now we are focusing on transformer-based models and do not support LSTM yet.

**Comment by trangtv57** [comment]
tks you for your answer, keep working great guys.
