### ISSUE TITLE
Support for Hugging Face's PEGASUS Model

### ISSUE THREAD

**Issue by AlfredWGA** [microsoft/fastseq#98]
Hi,

Thank you for the excellent work. Do you have plans to support Hugging Face's PEGASUS, such as `google/pegasus-large`?

Thank you.

**Comment by JiushengChen** [comment]
Thanks for your interest! Yes, it is in our plan. But we have many to-do items, will triage internally. If more people has interest in this model, we can prioritize it.

**Comment by AlfredWGA** [comment]
@JiuqingSong Thank you for the response. PEGASUS is a popular model for text generation so I'm looking forward to seeing it. Also, is there a way that I can see the full list of supported models? For example, in your GPT2 example you used HF's `gpt2`, and there're many versions of GPT2 on HF model hub, including `gpt2-medium`, `gpt2-large`, and user-uploaded model like `antoiloui/belgpt2`, how can I know if they're also supported?

**Comment by feihugis** [comment]
> @JiuqingSong Thank you for the response. PEGASUS is a popular model for text generation so I'm looking forward to seeing it. Also, is there a way that I can see the full list of supported models? For example, in your GPT2 example you used HF's `gpt2`, and there're many versions of GPT2 on HF model hub, including `gpt2-medium`, `gpt2-large`, and user-uploaded model like `antoiloui/belgpt2`, how can I know if they're also supported?

@AlfredWGA Good suggestion. I will add a full list of supported models.

**Comment by JiuqingSong** [comment]
I believe you are "at"ing wrong person.

**Comment by AlfredWGA** [comment]
> I believe you are "at"ing wrong person.

Sorry about that. Just fix it 😄

**Comment by AlfredWGA** [comment]
@JiuqingSong Sorry about that, just fixed it.

**Comment by AlfredWGA** [comment]
@feihugis Thank you, that'll be a great help.
