### ISSUE TITLE
Support for current fairseq 0.10.2

### ISSUE THREAD

**Issue by alaneckhardt** [microsoft/fastseq#99]
Supported version of fairseq is 0.9.0, from late 2019. Current version has some breaking API changes. Is it planned to update fastseq to support current fairseq?
Thanks!

**Comment by feihugis** [comment]
@alaneckhardt Supporting the latest version of fairseq is on our todo list. Currently we are collecting info from the community to set priorities.

**Comment by alaneckhardt** [comment]
Thanks! I will wait for your decision.

**Comment by WQtong** [comment]
Hi Any updates on the plan? Currently if I downgrade the fairseq to 0.9.0 it throws error. If this tool does not support the newest fairse, it can not be used. Thank you.

**Comment by feihugis** [comment]
@WQtong Sorry about the issues. Our team is fully occupied by some other tasks (e.g., developing cuda kernels to speed up the inference). We may not be able to support the latest version of fairseq in a short period. However, the contributions from the community are very welcome!

**Comment by feihugis** [comment]
@WQtong @alaneckhardt  FYI, we are working on the support of fairseq-0.10.2.

**Comment by leminhyen2** [comment]
I tested that branch however the performance is even slower than the stock fairseq. The below code uses a base Transformer to translate a list of 30 sentences in 0.87 seconds while after adding "import fastseq" as the first line, the performance drops to 0.95 seconds. (this was tested on a Google Colab P100)

from fairseq.models.transformer import TransformerModel
import time 

ja2en = TransformerModel.from_pretrained(
    './gdrive/MyDrive/japaneseModel/',
    checkpoint_file='big.pretrain.pt',
    data_name_or_path='./',
    bpe='sentencepiece',
    sentencepiece_model='./gdrive/MyDrive/japaneseModel/spm.en.nopretok.model',
    is_gpu = True
)
ja2en.cuda()

**Comment by feihugis** [comment]
> I tested that branch however the performance is even slower than the stock fairseq. The below code uses a base Transformer to translate a list of 30 sentences in 0.87 seconds while after adding "import fastseq" as the first line, the performance drops to 0.95 seconds. (this was tested on a Google Colab P100)
> 
> from fairseq.models.transformer import TransformerModel
> import time
> 
> ja2en = TransformerModel.from_pretrained(
> './gdrive/MyDrive/japaneseModel/',
> checkpoint_file='big.pretrain.pt',
> data_name_or_path='./',
> bpe='sentencepiece',
> sentencepiece_model='./gdrive/MyDrive/japaneseModel/spm.en.nopretok.model',
> is_gpu = True
> )
> ja2en.cuda()

@leminhyen2 Does your model run the forward process only once without beam search? If yes, it may be expected. Some details can be found [here](https://github.com/microsoft/fastseq/issues/87#issuecomment-844595844). If not, could you create an issue to describe more details for us to reproduce? and we can discuss more details there.

**Comment by leminhyen2** [comment]
@feihugis by forward process, you mean running the translate command like below? That is how I did it but with 30 sentences
```
listOfJapaneseSentences = ["こんにちは", "はい"]
resultList = ja2en.translate(listOfJapaneseSentences )
print(resultList)
```
How do I add beam search to this case? or is this only possible with command line of fairseq or fastseq?

**Comment by alaneckhardt** [comment]
I verified current fastseq works with fairseq 0.10.2., thanks a lot!

However I couldn't confirm the speedup - I tried our fairseq model train on en-cs data. fastseq was slower for batch size 1 (3m43 vs 3m23),  about the same for batch size 10 (1m28 vs 1m24) and very slightly faster for batch size 100 (0m36 vs 0m39).
I followed https://github.com/microsoft/fastseq/blob/main/examples/wmt/README.md#setting about how to run fastseq and compare it to fairseq and used pytorch 1.10.0 with CUDA 10.2. GPU was Tesla T4.

**Comment by alaneckhardt** [comment]
Maybe if you can specify how the conda environment was created, I could pinpoint where the things went wrong.
Unfortunately, the link to WMT'16 en-de data from the examples doesn't work anymore, so I couldn't run it using your model.

**Comment by feihugis** [comment]
@alaneckhardt  Could you please try a larger batch size (e.g., 256) as [this table](https://github.com/microsoft/fastseq/tree/main/examples/wmt#speedup-by-using-fastseq)? We use the largest batch size to measure the performance. The reason is that FastSeq optimizes the gpu memory usage and operations to allow the larger batch size to improve the throughput. Currently the latency related issues are not our focus yet (but maybe in the future).

In terms of the environment setup, you can use this dockerfile (https://github.com/microsoft/fastseq/blob/main/docker/Dockerfile). The benchmarking script we used to measure the performance can be found [here](https://github.com/microsoft/fastseq/blob/main/benchmarks/models/fs_wmt.sh). You should be able to run it by `cd fastseq/benchmarks && ./models/fs_wmt.sh`.

We will also resolve the data link issue you reported soon..
